services:
  jekyllbuild:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build_command: "bundle exec jekyll serve --host 0.0.0.0 --port 4000 --watch --trace"
    volumes:
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      - JEKYLL_ENV=production
